export const mtmDescriptions: Record<string, string> = {
  "fingering": `Ten rivets (two rows of five rivets) are to be moved to corresponding holes on the finger dexterity\nboard. The board is set so the rivets are moved from the front 5 holes and moved to the back 5\nholes. Instruct the evaluee to start with their hand ready. Reach to the next rivet, etc., until all five\nrivets in each of two rows have been moved and the hand returns to the start/stop switch. The\nevaluee is required to pick up any dropped pieces and continue until the task is completed, but\nplease note any mishandling in the comments section.`,

  "bi-manual-fingering": `Ten rivets (two rows of five rivets) are to be moved by each hand (20 rivets in total) to\ncorresponding holes on the dexterity board. The board is set so the rivets are placed in the back 5\nholes and moved to the front 5 holes. Instruct the evaluee to start. Reach to the next rivets, etc.,\nuntil all five rivets in each row have been moved and the hand returns to the start/stop switch. The\nevaluee is required to pick up any dropped pieces and continue until the task is completed, but\nplease note any mishandling in the comments section.`,

  "handling": `Instruct the evaluee to stand in front of the dexterity cube, position their hand ready to push the\nstart switch placed in the center front of the dexterity cube. After pressing the start button the\nevaluee reaches and moves each peg in the following manner. Continue moving pegs from front to\nback until that row has been completed, then reach to the front most peg in the second row and\nrepeat until all 12 pegs have been moved. The last motion is to return the hand to push the\nstart/stop switch. The evaluee is required to pick up any dropped pieces and continue until the task\nis completed, but please note any mishandling in the comments section.`,

  "bi-manual-handling": `Instruct the evaluee to stand in front of the dexterity cube, position their hand ready to push the\nstart switch placed in the center front of the dexterity cube. After pressing the start button the\nevaluee reaches with both hands and moves pairs of peg. Move the hands to the next pegs and\ncontinue until all 12 pegs are in their receiving holes. The last motion is to return the hand to push\nthe start/stop switch. The evaluee is required to pick up any dropped pieces and continue until the\ntask is completed, but please note any mishandling in the comments section.`,

  "reach-immediate": `Start the timer when the hand leaves the chest. Perform a fully extended reach to the front in the\nIMMEDIATE plane, starting with the hand at the center of the chest, making 6 (or as prescribed)\nreturn trips with the arm. Stop the timer when the hand touches the chest on the 6th (or as\nprescribed) return trip.`,

  "reach-overhead": `Start the timer when the hand leaves the chest. Perform a fully extended reach to the front in the\nOVERHEAD plane, starting with the hand at the center of the chest, making 6 (or as prescribed)\nreturn trips with the arm. Stop the timer when the hand touches the chest on the 6th (or as\nprescribed) return trip.`,

  "reach-with-weight": `Instruct the evaluee to move 4 - 1 Lb. Weights from the front of the dexterity cube, to the top of the\ncube. This test can be performed with the right or left arm. The timer starts when the evaluee\npushes the start switch. Move the weights one at a time (from right to left) from the inside bottom of\nthe box, placing the weights on the top of the box (from right to left). When all 4 weights are placed\non top of the box reach to the top right weight and return the weights. The timer stops when the\nhand presses the start/stop switch. The evaluee is required to pick up any dropped weights and\ncontinue until the task is completed, but please note any mishandling in the comments section.`,

  "balance": `Instruct the evaluee to walk a straight line you have taped on the floor, placing one foot in front of\nthe other at a comfortable pace, with the trailing foot placed close to the leading foot, a few inches\nfrom each other. Begin the timer. Continue placing one foot in front of the other at a comfortable\npace, with the trailing foot placed a few inches from the leading foot. Stop the timer when the\nleading foot finishes the 10th (or as prescribed) pace, but have the evaluee continue walking\nthrough the last pace motion.`,

  "stoop": `Instruct the evaluee to stand in front of a knuckle height shelf with a hand weight (less than 2 lb.)\ngrasped in the dominant hand. Start the timer when the hand with the weight leaves the shelf.\nStoop (bend) to touch the weight to the floor, (within 6 inches of the floor is acceptable), then arise\nfrom the stoop position and touch the weight to the knuckle height shelf and continue for a total of 6\n(or as prescribed) return trips with the weight. Stop the timer when the weight touches the shelf on\nthe 6th (or as prescribed) return trip.`,

  "crouch": `Instruct the evaluee to assume a crouch position, with a hand weight (less than 2 lb.) grasped in\nthe dominant hand. While maintaining a crouch position, the evaluee will move the weight from the\n12 inch height shelf to the floor then back to the 12 inch. Continue for a total of 6 (or as prescribed)\nreturn trips with the weight. Stop when the weight touches the shelf on the 6th (or as prescribed)\nreturn trip.`,

  "crawl": `Instruct the evaluee to crawl the prescribed distance. Begin timer when the leading hand crosses\nthe start line. Crawl the prescribed distance. Stop the timer when the leading hand crosses the\nstop line.`,

  "kneel": `Instruct the evaluee to stand in front of a knuckle height shelf with a hand weight (less than 2 lb.)\ngrasped in the dominant hand. Start the timer when the hand with the weight leaves the shelf.\nKneel to one knee on the floor, with the hand weight grasped in the dominant hand and while\nremaining in that one leg kneel position, move the hand weight grasped in the dominant hand from\nthe 12 inch high shelf to the floor and back to the 12 inch high shelf.`,

  "walk": `Start the timer when the leading foot crosses the start line. Walk the prescribed distance, turn 180\ndegrees, walk the return distance, turn 180 degrees, repeating the walking activity until three (or as\nprescribed) return trips have been completed. Stop the timer when the leading foot crosses the\nstop line on the return of the third (or as prescribed) return trip.`,

  "carry": `Start the timer when the evaluee lifts the container from the knuckle height shelf. Turn 180\ndegrees to walk the prescribed distance, turn and walk the return distance. Stop the timer when the\nevaluee crosses the return line, before they place the container back to the shelf.`,

  "climb-stairs": `Begin timing when the leading foot leaves the landing. Walk up a flight of stairs using the foot over\nfoot method. Stop the timer when the trailing foot reaches the top landing.`,

  "push-pull-cart": `Instruct the evaluee to push and then pull the weighted container on a cart through the prescribed\ndistance. As the start and stop time of this test can vary greatly, depending on floor surfaces, cart\ncondition etc. At least 8 feet of full motion push or pull action should be sampled. Stop the timer\nwhen the cart leading edge reaches the stop line, allowing the slowdown time to occur after the\nstop line.`
};
