export const mtmDescriptions: Record<string, string> = {
  "fingering": `Ten rivets (two rows of five rivets) are to be moved to corresponding holes on the finger dexterity board. The board is set so the rivets are moved from the front 5 holes and moved to the back 5 holes. Instruct the evaluee to start with their hand ready, reach to the next rivet, and continue until all five rivets in each of the two rows have been moved and the hand returns to the start/stop switch. The evaluee is required to pick up any dropped pieces and continue until the task is completed; note any mishandling in the comments section.`,

  "bi-manual-fingering": `Ten rivets (two rows of five rivets per hand; 20 rivets total) are to be moved by each hand to corresponding holes on the dexterity board. The board is set so the rivets are placed in the back five holes and moved to the front five holes. Instruct the evaluee to start, reach to the next rivet, and continue until all rivets in each row have been moved and the hand returns to the start/stop switch. The evaluee must pick up any dropped pieces and continue until the task is completed; note any mishandling in the comments section.`,

  "handling": `Instruct the evaluee to stand in front of the dexterity cube with their hand ready to push the start switch located front-center on the cube. After pressing the start button the evaluee reaches and moves each peg in sequence, moving pegs from front to back until that row is complete, then proceeds to the next row until all 12 pegs have been moved. The final motion is to return the hand to the start/stop switch. The evaluee is required to pick up any dropped pieces and continue until the task is completed; note any mishandling in the comments section.`,

  "bi-manual-handling": `Instruct the evaluee to stand in front of the dexterity cube with their hands ready to press the start switch. After pressing the start button the evaluee reaches with both hands to move pairs of pegs, advancing to the next pairs until all 12 pegs are placed in their receiving holes. The final motion is to return the hands to the start/stop switch. The evaluee is required to pick up any dropped pieces and continue until the task is completed; note any mishandling in the comments section.`,

  "reach-immediate": `Start the timer when the hand leaves the chest. Perform a fully extended reach to the front in the immediate plane, beginning with the hand at the center of the chest and making the prescribed number of return trips (typically six). Stop the timer when the hand touches the chest on the final prescribed return trip.`,

  "reach-overhead": `Start the timer when the hand leaves the chest. Perform a fully extended reach overhead in the prescribed plane, beginning with the hand at the center of the chest and making the prescribed number of return trips (typically six). Stop the timer when the hand touches the chest on the final prescribed return trip.`,

  "reach-with-weight": `Instruct the evaluee to move four 1-lb weights from the front of the dexterity cube to the top of the cube; the test may be performed with the right or left arm. The timer starts when the evaluee presses the start switch. Move the weights one at a time from the inside bottom of the box to the top of the box in sequence. After placing all weights on top, reach to the top right weight and return the weights as prescribed. The timer stops when the hand presses the start/stop switch. The evaluee is required to pick up any dropped weights and continue until the task is completed; note any mishandling in the comments section.`,

  "balance": `Instruct the evaluee to walk a straight line marked on the floor, placing one foot in front of the other at a comfortable pace so the trailing foot is close to the leading foot. Begin the timer and continue placing one foot in front of the other for the prescribed number of paces (typically ten). Stop the timer when the leading foot completes the final prescribed pace, while allowing the evaluee to continue through the last motion.`,

  "stoop": `Instruct the evaluee to stand in front of a knuckle-height shelf holding a hand weight (less than 2 lb) in the dominant hand. Start the timer when the weighted hand leaves the shelf. The evaluee stoops to touch the weight to the floor (within 6 inches of the floor is acceptable), then returns the weight to the knuckle-height shelf and repeats for the prescribed number of return trips (typically six). Stop the timer when the weight touches the shelf on the final prescribed return trip.`,

  "crouch": `Instruct the evaluee to assume and maintain a crouch position while holding a hand weight (less than 2 lb) in the dominant hand. While maintaining the crouch, move the weight from a 12-inch shelf to the floor and back to the 12-inch shelf for the prescribed number of return trips (typically six). Stop the timer when the weight touches the shelf on the final prescribed return trip.`,

  "crawl": `Instruct the evaluee to crawl the prescribed distance. Begin timing when the leading hand crosses the start line and stop the timer when the leading hand crosses the stop line. Follow the specified distance and technique instructions.`,

  "kneel": `Instruct the evaluee to stand in front of a knuckle-height shelf holding a hand weight (less than 2 lb) in the dominant hand. Start the timer when the weighted hand leaves the shelf. The evaluee kneels to one knee and, while remaining in that position, moves the weight from the 12-inch shelf to the floor and back to the 12-inch shelf as prescribed. Stop timing according to the test protocol.`,

  "walk": `Start the timer when the leading foot crosses the start line. Walk the prescribed distance, turn 180 degrees, and walk the return distance, repeating until the prescribed number of return trips (typically three) is completed. Stop the timer when the leading foot crosses the stop line on the final return trip.`,

  "carry": `Start the timer when the evaluee lifts the container from the knuckle-height shelf. Turn and walk the prescribed distance, then return to the start. Stop the timer when the evaluee crosses the return line, before placing the container back on the shelf. Note any deviations in lifting, carrying technique, or safety.`,

  "climb-stairs": `Begin timing when the leading foot leaves the landing. The evaluee ascends (and/or descends) a flight of stairs using a controlled foot-over-foot technique. Observe and record body positioning, handrail use, step clearance, and any loss of balance or compensatory movements. Stop the timer when the trailing foot reaches the top landing or when the leading foot crosses the bottom landing on descent, as prescribed by protocol.`,

  "climb-ladder": `Begin timing when the leading foot leaves the landing. The evaluee ascends and/or descends a ladder using a safe, controlled foot-over-foot technique while maintaining three points of contact (two hands and one foot or two feet and one hand) where possible. Observe and record body positioning (avoid overreaching), hand placement, use of rails, step clearance, and any loss of balance or compensatory movements. Time the ascent and descent as prescribed; stop the timer when the trailing foot reaches the top landing (or when the leading foot crosses the bottom landing on descent), and note any deviations from safe technique. Follow industry ladder safety guidance (OSHA) and ensure the ladder and landings are secure before testing.`,

  "push-pull-cart": `Instruct the evaluee to push and then pull the weighted container on a cart through the prescribed distance. Because start and stop times vary with surface and cart condition, sample at least eight feet of full motion push or pull action. Stop the timer when the cart leading edge reaches the stop line and allow deceleration to occur after the stop line. Note any irregularities in motion or cart control.`,
};
